const config = {
  version: '0.1.0',
  lights: [
    {
      type: 'HemisphereLight',
      color: 16777215,
      groundColor: 2171169,
      intensity: 0.7,
    },
  ],
  textures: [
    {
      name: '22_brake_disc_map_c.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: '27_inner.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: '28_inner_chair.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: 'AO.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: 'car_map.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: 'hot-dot.png',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: 'inner_door.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: 'inner_map_c_wutianchuang.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: 'plane_map_c.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: 'tire_map_c.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: 'tire_map_color.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: 'scene.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: '17_plane_map_c.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: 'car_map.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: 'inner.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: 'inner_1.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: 'inner_chair.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: 'inner_door.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: '27_inner.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: '17_plane_map_c.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: 'inner.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: 'inner_1.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: 'inner_chair.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: 'inner_door.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: 'car_map_open.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: 'inner_chair_yellow.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: 'inner_door_yellow.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: 'inner_yellow.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: '11_headlight_plastic.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: 'changjing1.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: 'changjin2.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: 'scene1.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: '22_brake_disc_map_c.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
    {
      name: '22_brake_disc_map_c_red.jpg',
      repeat: {
        x: 1,
        y: 1,
      },
    },
  ],
  hdrs: [
    {
      name: 'piece-nb-40.hdr',
    },
    {
      name: 'piece-nb-40.hdr',
    },
    {
      name: 'studio_001.hdr',
    },
    {
      name: 'studio_001.hdr',
    },
    {
      name: 'ceshi1.hdr',
    },
    {
      name: 'ceshi1.hdr',
    },
  ],
  cubes: [
    {
      name: 'env',
    },
    {
      name: 'glass',
    },
    {
      name: 'ENV1',
    },
    {
      name: 'env2',
    },
  ],
  models: [
    {
      name: 'dashuifa.glb',
      meshs: [
        {
          name: '02_car_glass',
          visible: true,
          material: 'glass——white',
        },
        {
          name: '04_car_black_plastic',
          visible: true,
          material: 'car_plastic_black',
        },
        {
          name: '54_trunk_black_plastic',
          visible: true,
          material: 'car_plastic_black',
        },
        {
          name: '31_lf_door_glass',
          visible: true,
          material: 'glass——white',
        },
        {
          name: '38_lb_door_glass',
          visible: true,
          material: 'glass——white',
        },
        {
          name: '15_taillight_red_1',
          visible: true,
          material: 'chrome_red',
        },
        {
          name: '14_taillight_black_plastic',
          visible: true,
          material: 'red_1',
        },
        {
          name: '16_taillight_red_2',
          visible: true,
          material: 'chrome_red-2',
        },
        {
          name: '36_lb_door_chrome',
          visible: true,
          material: 'chrome',
        },
        {
          name: '33_lf_door_plastic',
          visible: true,
          material: 'car_plastic',
        },
        {
          name: '37_lb_door_plastic',
          visible: true,
          material: 'car_plastic',
        },
        {
          name: '03_car_plastic',
          visible: true,
          material: 'car_plastic',
        },
        {
          name: '56_trunk_plastic',
          visible: true,
          material: 'car_plastic',
        },
        {
          name: '19_hub_before_chrome',
          visible: false,
          material: 'chrome_mosha',
        },
        {
          name: '17_brake_disc_map_c',
          visible: true,
          material: 'brake_disc_map_c',
        },
        {
          name: '30_lf_door_black_plastic',
          visible: true,
          material: 'car_plastic_black',
        },
        {
          name: '32_lf_door_mirror',
          visible: true,
          material: 'mirror',
        },
        {
          name: '05_car_chrome',
          visible: true,
          material: 'chrome',
        },
        {
          name: '09_headlight_chrome',
          visible: true,
          material: 'open_light',
        },
        {
          name: '07_light_glass',
          visible: true,
          material: 'light_glass',
        },
        {
          name: '06_car_plane',
          visible: true,
          material: 'yinying',
        },
        {
          name: '11_car_logo_white',
          visible: true,
          material: 'white',
        },
        {
          name: '21_hub_before_white',
          visible: false,
          material: 'white',
        },
        {
          name: '13_car_di_black',
          visible: true,
          material: 'car_plastic_hui',
        },
        {
          name: '53_trunk_chrome',
          visible: true,
          material: 'chrome',
        },
        {
          name: '20_hub_before_black_plastic',
          visible: false,
          material: 'car_plastic_black',
        },
        {
          name: '18_before_tire',
          visible: true,
          material: 'luntai',
        },
        {
          name: '22_after_tire',
          visible: true,
          material: 'luntai',
        },
        {
          name: '25_hub_after_white',
          visible: false,
          material: 'white',
        },
        {
          name: '23_hub_after_chrome',
          visible: false,
          material: 'chrome_mosha',
        },
        {
          name: '24_hub_after_black_plastic',
          visible: false,
          material: 'car_plastic_black',
        },
        {
          name: '43_rf_door_plastic',
          visible: true,
          material: 'car_plastic',
        },
        {
          name: '42_rf_door_black_plastic',
          visible: true,
          material: 'car_plastic_black',
        },
        {
          name: '29_lf_door_chrome',
          visible: true,
          material: 'chrome',
        },
        {
          name: '45_rf_door_glass',
          visible: true,
          material: 'glass——white',
        },
        {
          name: '49_rb_door_plastic',
          visible: true,
          material: 'car_plastic',
        },
        {
          name: '48_rb_door_chrome',
          visible: true,
          material: 'chrome',
        },
        {
          name: '50_rb_door_glass',
          visible: true,
          material: 'glass——white',
        },
        {
          name: '34_lf_door_inner',
          visible: true,
          material: 'inner_door',
        },
        {
          name: '39_lb_door_glass',
          visible: true,
          material: 'inner_door',
        },
        {
          name: '46_rf_door_inner',
          visible: true,
          material: 'inner_door',
        },
        {
          name: '51_rb_door_inner',
          visible: true,
          material: 'inner_door',
        },
        {
          name: '55_trunk_inner',
          visible: true,
          material: 'inner_door',
        },
        {
          name: '27_car_inner_chair',
          visible: true,
          material: 'inner_chair',
        },
        {
          name: '26_car_inner',
          visible: true,
          material: 'inner',
        },
        {
          name: '44_rf_door_mirror',
          visible: true,
          material: 'mirror',
        },
        {
          name: '08_headlight_black_plastic',
          visible: true,
          material: 'car_plastic_black',
        },
        {
          name: '41_rf_door_chrome',
          visible: true,
          material: 'chrome',
        },
        {
          name: '57_changjing',
          visible: true,
          material: 'changjing',
        },
        {
          name: '28_lf_door_body',
          visible: true,
          material: 'car_paint_white',
        },
        {
          name: '01_car_body',
          visible: true,
          material: 'car_paint_white',
        },
        {
          name: '52_trunk_body',
          visible: true,
          material: 'car_paint_white',
        },
        {
          name: '35_lb_door_body',
          visible: true,
          material: 'car_paint_white',
        },
        {
          name: '47_rb_door_body',
          visible: true,
          material: 'car_paint_white',
        },
        {
          name: '12_car_map',
          visible: true,
          material: 'car_map',
        },
        {
          name: '90_qidong_1',
          visible: false,
          material: 'qidong_home',
        },
        {
          name: '91_qidong_2',
          visible: false,
          material: 'qidong_beijing',
        },
        {
          name: '92_qidong_3',
          visible: false,
          material: 'qidong_road',
        },
        {
          name: '93_qidong_4',
          visible: false,
          material: 'qidong_baixian',
        },
        {
          name: '58_hub_before_black_plastic',
          visible: true,
          material: 'car_plastic_black',
        },
        {
          name: '60_hub_before_white',
          visible: true,
          material: 'white',
        },
        {
          name: '59_hub_before_chrome',
          visible: true,
          material: 'chrome',
        },
        {
          name: '61_hub_after_black_plastic',
          visible: true,
          material: 'car_plastic_black',
        },
        {
          name: '63_hub_after_white',
          visible: true,
          material: 'white',
        },
        {
          name: '62_hub_after_chrome',
          visible: true,
          material: 'chrome',
        },
        {
          name: '02_car_glass_black',
          visible: true,
          material: 'glass——white',
        },
        {
          name: '65_car_leida',
          visible: true,
          material: 'chrome_hub_plastic',
        },
        {
          name: '05_car_headlight_chrome',
          visible: true,
          material: 'light_chrome',
        },
        {
          name: '40_rf_door_body',
          visible: true,
          material: 'car_paint_white',
        },
        {
          name: '53_trunk_chrome_1',
          visible: true,
          material: 'chrome',
        },
        {
          name: '66_car_leida_chrome_siqu',
          visible: false,
          material: 'chrome',
        },
        {
          name: '67_car_leida_plastic_siqu',
          visible: false,
          material: 'car_plastic_black',
        },
        {
          name: '33_lf_door_plastic_1',
          visible: true,
          material: 'car_plastic',
        },
        {
          name: '37_lb_door_plastic_1',
          visible: true,
          material: 'car_plastic',
        },
        {
          name: '28_lf_door_body_1',
          visible: true,
          material: 'car_paint_white',
        },
        {
          name: '35_lb_door_body_1',
          visible: true,
          material: 'car_paint_white',
        },
        {
          name: '43_rf_door_plastic_1',
          visible: true,
          material: 'car_plastic',
        },
        {
          name: '40_rf_door_body_1',
          visible: true,
          material: 'car_paint_white',
        },
        {
          name: '49_rb_door_plastic_1',
          visible: true,
          material: 'car_plastic',
        },
        {
          name: '47_rb_door_body_1',
          visible: true,
          material: 'car_paint_white',
        },
        {
          name: '10_headlight_chrome_1',
          visible: true,
          material: 'hub_chrome_mosha',
        },
        {
          name: '03_car_plastic_dipei',
          visible: true,
          material: 'car_plastic',
        },
        {
          name: '03_car_plastic_siqu',
          visible: false,
          material: 'car_plastic',
        },
        {
          name: '65_car_leida_1',
          visible: false,
          material: 'chrome_hub_plastic',
        },
        {
          name: '26_car_inner_red',
          visible: false,
          material: 'inner',
        },
        {
          name: '27_car_inner_chair_1',
          visible: false,
          material: 'inner_chair',
        },
        {
          name: '34_lf_door_inner_1',
          visible: false,
          material: 'inner_door',
        },
        {
          name: '46_rf_door_inner_1',
          visible: false,
          material: 'inner_door',
        },
      ],
    },
  ],
  materials: [
    {
      type: 'MeshPhysicalMaterial',
      name: 'glass',
      color: 1184274,
      opacity: 0.6,
      transparent: true,
      reflectivity: 1,
      metalness: 1,
      clearcoat: 0.9,
      clearcoatRoughness: 0.05,
      envMap: 'glass',
      displacementBias: 0,
      transmission: 0,
      attenuationDistance: 0,
      thickness: 0,
      vertexColors: false,
      side: 2,
      flatShading: false,
      alphaTest: 0,
      wireframe: false,
      sheen: 1,
    },
    {
      type: 'MeshPhongMaterial',
      name: 'light_glass',
      opacity: 0.35,
      transparent: true,
      emissive: 1579032,
      reflectivity: 10.35,
      envMap: 'ENV1',
      displacementBias: 0,
      emissiveIntensity: 1.7,
      vertexColors: false,
      side: 0,
      flatShading: false,
      combine: 0,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshPhysicalMaterial',
      name: 'glass——white',
      color: 13027014,
      opacity: 0.2,
      transparent: true,
      reflectivity: 1,
      metalness: 1,
      clearcoat: 0.9,
      clearcoatRoughness: 0.05,
      envMap: 'glass',
      displacementBias: 0,
      transmission: 0,
      attenuationDistance: 0,
      thickness: 0,
      vertexColors: false,
      side: 2,
      flatShading: false,
      alphaTest: 0,
      wireframe: false,
      sheen: 1,
    },
    {
      type: 'MeshPhongMaterial',
      name: 'chrome',
      transparent: false,
      specular: 16711422,
      emissive: 8360103,
      reflectivity: 0.9,
      envMap: 'env2',
      aoMapIntensity: 0.3,
      displacementBias: 0,
      emissiveIntensity: 2.2,
      vertexColors: false,
      side: 0,
      flatShading: false,
      combine: 0,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshPhongMaterial',
      name: 'chrome_hub',
      color: 13828096,
      transparent: false,
      specular: 16711422,
      emissive: 1973790,
      reflectivity: 0.9,
      envMap: 'env2',
      aoMapIntensity: 0.3,
      displacementBias: 0,
      emissiveIntensity: 2.2,
      vertexColors: false,
      side: 0,
      flatShading: false,
      combine: 0,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshLambertMaterial',
      name: 'chrome_red',
      color: 16318464,
      transparent: false,
      emissive: 16711680,
      envMap: 'env2',
      emissiveIntensity: 3,
      vertexColors: false,
      side: 0,
      combine: 0,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshPhongMaterial',
      name: 'chrome_red-2',
      color: 11599872,
      transparent: false,
      specular: 16777215,
      emissive: 11403264,
      reflectivity: 0.9,
      envMap: 'env2',
      aoMapIntensity: 0.3,
      displacementBias: 0,
      emissiveIntensity: 1.6,
      vertexColors: false,
      side: 0,
      flatShading: false,
      combine: 0,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshPhongMaterial',
      name: 'mirror',
      color: 15332095,
      transparent: false,
      specular: 0,
      shininess: 60,
      emissive: 7238003,
      reflectivity: 1.2,
      envMap: 'glass',
      displacementBias: 0,
      vertexColors: false,
      side: 0,
      flatShading: false,
      combine: 0,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshPhysicalMaterial',
      name: 'car_paint_black',
      color: 0,
      transparent: false,
      emissive: 131587,
      reflectivity: 1,
      roughness: 0.5,
      metalness: 1,
      clearcoat: 1,
      clearcoatRoughness: 0.05,
      map: 'AO.jpg',
      aoMap: 'AO.jpg',
      aoMapIntensity: 0.6,
      roughnessMap: 'AO.jpg',
      displacementBias: 0,
      transmission: 0,
      attenuationDistance: 0,
      thickness: 0,
      vertexColors: false,
      side: 0,
      flatShading: false,
      alphaTest: 0,
      wireframe: false,
      sheen: 0,
    },
    {
      type: 'MeshPhysicalMaterial',
      name: 'car_paint_gray',
      color: 11916543,
      transparent: false,
      reflectivity: 1,
      roughness: 0.5,
      metalness: 1,
      clearcoat: 1,
      clearcoatRoughness: 0.05,
      envMapIntensity: 0.7,
      map: 'AO.jpg',
      aoMap: 'AO.jpg',
      aoMapIntensity: 0.2,
      roughnessMap: 'AO.jpg',
      displacementBias: 0,
      transmission: 0,
      attenuationDistance: 0,
      thickness: 0,
      vertexColors: false,
      side: 0,
      flatShading: false,
      alphaTest: 0,
      wireframe: false,
      sheen: 0,
    },
    {
      type: 'MeshPhysicalMaterial',
      name: 'car_paint_white',
      transparent: false,
      emissive: 6250335,
      reflectivity: 1,
      roughness: 0.55,
      metalness: 1,
      clearcoat: 1,
      clearcoatRoughness: 0.05,
      envMapIntensity: 0.8,
      map: 'AO.jpg',
      aoMap: 'AO.jpg',
      aoMapIntensity: 0.7,
      roughnessMap: 'AO.jpg',
      displacementBias: 0,
      transmission: 0,
      attenuationDistance: 0,
      thickness: 0,
      vertexColors: false,
      side: 0,
      flatShading: false,
      toneMapped: false,
      alphaTest: 0,
      wireframe: false,
      sheen: 0,
    },
    {
      type: 'MeshPhysicalMaterial',
      name: 'car_paint_blue',
      color: 77212,
      transparent: false,
      reflectivity: 1,
      roughness: 0.5,
      metalness: 1,
      clearcoat: 1,
      clearcoatRoughness: 0.05,
      map: 'AO.jpg',
      aoMap: 'AO.jpg',
      aoMapIntensity: 0.2,
      roughnessMap: 'AO.jpg',
      displacementBias: 0,
      transmission: 0,
      attenuationDistance: 0,
      thickness: 0,
      vertexColors: false,
      side: 0,
      flatShading: false,
      toneMapped: false,
      alphaTest: 0,
      wireframe: false,
      sheen: 0,
    },
    {
      type: 'MeshPhysicalMaterial',
      name: 'car_paint_green',
      color: 12084,
      transparent: false,
      reflectivity: 1,
      roughness: 0.5,
      metalness: 1,
      clearcoat: 1,
      clearcoatRoughness: 0.05,
      map: 'AO.jpg',
      aoMap: 'AO.jpg',
      aoMapIntensity: 0.2,
      roughnessMap: 'AO.jpg',
      displacementBias: 0,
      transmission: 0,
      attenuationDistance: 0,
      thickness: 0,
      vertexColors: false,
      side: 0,
      flatShading: false,
      alphaTest: 0,
      wireframe: false,
      sheen: 1,
    },
    {
      type: 'MeshPhysicalMaterial',
      name: 'car_paint_pink',
      color: 16758968,
      transparent: false,
      emissive: 1117196,
      reflectivity: 1,
      roughness: 0.5,
      metalness: 1,
      clearcoat: 1,
      clearcoatRoughness: 0.05,
      envMapIntensity: 1.1,
      map: 'AO.jpg',
      aoMap: 'AO.jpg',
      aoMapIntensity: 0.5,
      roughnessMap: 'AO.jpg',
      displacementBias: 0,
      transmission: 0,
      attenuationDistance: 0,
      thickness: 0,
      vertexColors: false,
      side: 0,
      flatShading: false,
      alphaTest: 0,
      wireframe: false,
      sheen: 1,
    },
    {
      type: 'MeshPhysicalMaterial',
      name: 'car_paint_purple',
      color: 14141439,
      transparent: false,
      emissive: 394503,
      reflectivity: 1,
      roughness: 0.5,
      metalness: 1,
      clearcoat: 1,
      clearcoatRoughness: 0.05,
      map: 'AO.jpg',
      aoMap: 'AO.jpg',
      aoMapIntensity: 0.7,
      roughnessMap: 'AO.jpg',
      displacementBias: 0,
      transmission: 0,
      attenuationDistance: 0,
      thickness: 0,
      vertexColors: false,
      side: 0,
      flatShading: false,
      alphaTest: 0,
      wireframe: false,
      sheen: 1,
    },
    {
      type: 'MeshBasicMaterial',
      name: 'inner',
      transparent: false,
      map: 'inner.jpg',
      vertexColors: false,
      side: 0,
      combine: 0,
      toneMapped: false,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshBasicMaterial',
      name: 'inner_chair',
      transparent: false,
      reflectivity: 0,
      map: 'inner_chair.jpg',
      vertexColors: false,
      side: 0,
      combine: 0,
      toneMapped: false,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshBasicMaterial',
      name: 'inner_door',
      transparent: false,
      map: 'inner_door.jpg',
      vertexColors: false,
      side: 0,
      combine: 0,
      toneMapped: false,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshBasicMaterial',
      name: 'car_map',
      color: 13816530,
      transparent: false,
      map: 'car_map.jpg',
      vertexColors: false,
      side: 0,
      combine: 0,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshBasicMaterial',
      name: 'brake_disc_map_c',
      color: 6447714,
      transparent: false,
      map: '22_brake_disc_map_c.jpg',
      vertexColors: false,
      side: 0,
      combine: 0,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshPhongMaterial',
      name: 'car_plastic',
      color: 4539717,
      transparent: false,
      shininess: 2.8,
      reflectivity: 0.2,
      envMap: 'glass',
      displacementBias: 0,
      vertexColors: false,
      side: 0,
      flatShading: false,
      combine: 0,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshPhongMaterial',
      name: 'car_plastic_black',
      color: 11250346,
      transparent: false,
      emissive: 526602,
      envMap: 'env2',
      displacementBias: 0,
      vertexColors: false,
      side: 2,
      flatShading: false,
      combine: 0,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshPhongMaterial',
      name: 'car_plastic_hui',
      color: 0,
      transparent: false,
      specular: 0,
      emissive: 394758,
      reflectivity: 0.3,
      envMap: 'glass',
      displacementBias: 0,
      vertexColors: false,
      side: 0,
      flatShading: false,
      combine: 0,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshPhysicalMaterial',
      name: 'tire_map',
      transparent: false,
      reflectivity: 1,
      roughness: 0.6,
      metalness: 0.4,
      clearcoat: 0.1,
      clearcoatRoughness: 0,
      envMap: 'ENV1',
      map: 'tire_map_color.jpg',
      normalMap: 'tire_map_c.jpg',
      normalScale: {
        x: 2,
        y: 2,
      },
      clearcoatNormalMap: 'tire_map_c.jpg',
      displacementBias: 0,
      transmission: 0,
      attenuationDistance: 0,
      thickness: 0,
      vertexColors: false,
      side: 0,
      flatShading: false,
      alphaTest: 0,
      wireframe: false,
      sheen: 0,
      sheenRoughness: 0.75,
    },
    {
      type: 'MeshBasicMaterial',
      name: 'yinying',
      transparent: true,
      map: 'plane_map_c.jpg',
      vertexColors: false,
      side: 0,
      blending: 5,
      blendSrc: 205,
      blendDst: 202,
      combine: 1,
      toneMapped: false,
      alphaTest: 0.5,
      wireframe: false,
    },
    {
      type: 'MeshBasicMaterial',
      name: 'luntai',
      transparent: false,
      reflectivity: 0.35,
      envMap: 'env2',
      map: 'tire_map_color.jpg',
      aoMapIntensity: 0.3,
      vertexColors: false,
      side: 0,
      combine: 0,
      toneMapped: false,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshPhysicalMaterial',
      name: 'chrome_mosha',
      color: 7766415,
      transparent: false,
      reflectivity: 1,
      roughness: 0.3,
      metalness: 1,
      clearcoat: 1,
      clearcoatRoughness: 1,
      envMapIntensity: 1.6,
      displacementBias: 0,
      transmission: 0,
      attenuationDistance: 0,
      thickness: 0,
      vertexColors: false,
      side: 0,
      flatShading: false,
      alphaTest: 0,
      wireframe: false,
      sheen: 1,
    },
    {
      type: 'SpriteMaterial',
      name: 'hotspot',
      map: 'hot-dot.png',
      vertexColors: false,
      side: 0,
      alphaTest: 0,
    },
    {
      type: 'MeshBasicMaterial',
      name: 'changjing',
      transparent: false,
      map: 'scene.jpg',
      aoMap: 'scene.jpg',
      aoMapIntensity: 0,
      alphaMap: 'scene.jpg',
      specularMap: 'scene.jpg',
      vertexColors: false,
      side: 0,
      combine: 0,
      alphaTest: 0,
      wireframe: false,
      refractionRatio: 1,
    },
    {
      type: 'MeshPhongMaterial',
      name: 'hub_chrome_mosha',
      color: 16770304,
      opacity: 0.95,
      transparent: false,
      specular: 0,
      emissive: 16777215,
      reflectivity: 1.15,
      envMap: 'env',
      displacementBias: 0,
      emissiveIntensity: 1.1,
      vertexColors: false,
      side: 0,
      flatShading: false,
      combine: 0,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshLambertMaterial',
      name: 'chrome_hub',
      transparent: false,
      emissive: 16777215,
      envMap: 'env2',
      emissiveIntensity: 1.9,
      vertexColors: false,
      side: 0,
      combine: 0,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshPhongMaterial',
      name: 'chrome_hub_plastic',
      color: 0,
      transparent: false,
      specular: 0,
      shininess: 1,
      emissive: 526344,
      reflectivity: 1.05,
      envMap: 'glass',
      displacementBias: 0,
      vertexColors: false,
      side: 0,
      flatShading: false,
      combine: 0,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshLambertMaterial',
      name: 'open_light',
      transparent: false,
      emissive: 16777215,
      reflectivity: 1.05,
      envMap: 'ENV1',
      emissiveIntensity: 3,
      vertexColors: false,
      side: 0,
      combine: 0,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshBasicMaterial',
      name: 'inner_yellow',
      transparent: false,
      map: 'inner_yellow.jpg',
      vertexColors: false,
      side: 0,
      combine: 0,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshBasicMaterial',
      name: 'inner_chair_yellow',
      transparent: false,
      map: 'inner_chair_yellow.jpg',
      vertexColors: false,
      side: 0,
      combine: 0,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshBasicMaterial',
      name: 'inner_door_yellow',
      transparent: false,
      map: 'inner_door_yellow.jpg',
      vertexColors: false,
      side: 0,
      combine: 0,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshStandardMaterial',
      name: 'qidong_road',
      transparent: false,
      metalness: 0,
      map: 'changjin2.jpg',
      displacementBias: 0,
      vertexColors: false,
      side: 0,
      flatShading: false,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshStandardMaterial',
      name: 'qidong_home',
      transparent: false,
      emissive: 2236962,
      metalness: 0,
      map: 'changjing1.jpg',
      displacementBias: 0,
      vertexColors: false,
      side: 0,
      flatShading: false,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshStandardMaterial',
      name: 'qidong_baixian',
      transparent: false,
      emissive: 16777215,
      metalness: 0,
      displacementBias: 0,
      vertexColors: false,
      side: 0,
      flatShading: false,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshStandardMaterial',
      name: 'qidong_beijing',
      transparent: false,
      metalness: 0,
      displacementBias: 0,
      vertexColors: false,
      side: 0,
      flatShading: false,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshBasicMaterial',
      name: 'scene1',
      transparent: false,
      map: 'scene1.jpg',
      vertexColors: false,
      side: 0,
      combine: 0,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshBasicMaterial',
      name: 'red_kaqian',
      color: 9342606,
      transparent: false,
      map: '22_brake_disc_map_c_red.jpg',
      vertexColors: false,
      side: 0,
      combine: 0,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshBasicMaterial',
      name: 'white',
      transparent: false,
      vertexColors: false,
      side: 0,
      combine: 0,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshLambertMaterial',
      name: 'red_1',
      color: 16711680,
      transparent: false,
      emissive: 6160384,
      envMap: 'env2',
      vertexColors: false,
      side: 0,
      combine: 0,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshLambertMaterial',
      name: 'light_chrome',
      transparent: false,
      emissive: 16777215,
      reflectivity: 1.05,
      envMap: 'env2',
      emissiveIntensity: 3,
      vertexColors: false,
      side: 0,
      combine: 0,
      alphaTest: 0,
      wireframe: false,
    },
    {
      type: 'MeshPhysicalMaterial',
      name: 'mosha_hub_new',
      color: 16711680,
      transparent: false,
      roughness: 0.5,
      metalness: 0.9,
      clearcoat: 1,
      clearcoatRoughness: 0.03,
      displacementBias: 0,
      transmission: 0,
      attenuationDistance: 0,
      thickness: 0,
      vertexColors: false,
      side: 0,
      flatShading: false,
      alphaTest: 0,
      wireframe: false,
      sheen: 0.6,
    },
  ],
  carpaints: [
    {
      name: 'white',
      materials: [
        {
          mesh: '01_car_body',
          material: 'car_paint_white',
        },
        {
          mesh: '47_rb_door_body',
          material: 'car_paint_white',
        },
        {
          mesh: '40_rf_door_body',
          material: 'car_paint_white',
        },
        {
          mesh: '35_lb_door_body',
          material: 'car_paint_white',
        },
        {
          mesh: '28_lf_door_body',
          material: 'car_paint_white',
        },
        {
          mesh: '52_trunk_body',
          material: 'car_paint_white',
        },
        {
          mesh: '47_rb_door_body_1',
          material: 'car_paint_white',
        },
        {
          mesh: '40_rf_door_body_1',
          material: 'car_paint_white',
        },
        {
          mesh: '35_lb_door_body_1',
          material: 'car_paint_white',
        },
        {
          mesh: '28_lf_door_body_1',
          material: 'car_paint_white',
        },
      ],
    },
    {
      name: 'hui',
      materials: [
        {
          mesh: '01_car_body',
          material: 'car_paint_gray',
        },
        {
          mesh: '28_lf_door_body',
          material: 'car_paint_gray',
        },
        {
          mesh: '35_lb_door_body',
          material: 'car_paint_gray',
        },
        {
          mesh: '40_rf_door_body',
          material: 'car_paint_gray',
        },
        {
          mesh: '47_rb_door_body',
          material: 'car_paint_gray',
        },
        {
          mesh: '52_trunk_body',
          material: 'car_paint_gray',
        },
        {
          mesh: '28_lf_door_body_1',
          material: 'car_paint_gray',
        },
        {
          mesh: '35_lb_door_body_1',
          material: 'car_paint_gray',
        },
        {
          mesh: '40_rf_door_body_1',
          material: 'car_paint_gray',
        },
        {
          mesh: '47_rb_door_body_1',
          material: 'car_paint_gray',
        },
      ],
    },
    {
      name: 'purple',
      materials: [
        {
          mesh: '01_car_body',
          material: 'car_paint_purple',
        },
        {
          mesh: '28_lf_door_body',
          material: 'car_paint_purple',
        },
        {
          mesh: '35_lb_door_body',
          material: 'car_paint_purple',
        },
        {
          mesh: '40_rf_door_body',
          material: 'car_paint_purple',
        },
        {
          mesh: '47_rb_door_body',
          material: 'car_paint_purple',
        },
        {
          mesh: '52_trunk_body',
          material: 'car_paint_purple',
        },
        {
          mesh: '47_rb_door_body_1',
          material: 'car_paint_purple',
        },
        {
          mesh: '40_rf_door_body_1',
          material: 'car_paint_purple',
        },
        {
          mesh: '35_lb_door_body_1',
          material: 'car_paint_purple',
        },
        {
          mesh: '28_lf_door_body_1',
          material: 'car_paint_purple',
        },
      ],
    },
    {
      name: 'pink',
      materials: [
        {
          mesh: '28_lf_door_body',
          material: 'car_paint_pink',
        },
        {
          mesh: '01_car_body',
          material: 'car_paint_pink',
        },
        {
          mesh: '52_trunk_body',
          material: 'car_paint_pink',
        },
        {
          mesh: '35_lb_door_body',
          material: 'car_paint_pink',
        },
        {
          mesh: '40_rf_door_body',
          material: 'car_paint_pink',
        },
        {
          mesh: '47_rb_door_body',
          material: 'car_paint_pink',
        },
        {
          mesh: '28_lf_door_body_1',
          material: 'car_paint_pink',
        },
        {
          mesh: '35_lb_door_body_1',
          material: 'car_paint_pink',
        },
        {
          mesh: '40_rf_door_body_1',
          material: 'car_paint_pink',
        },
        {
          mesh: '47_rb_door_body_1',
          material: 'car_paint_pink',
        },
      ],
    },
  ],
  variants: [
    {
      name: 'Forbidden status',
      visibles: ['57_changjing'],
      invisible: ['90_qidong_1', '91_qidong_2', '92_qidong_3', '93_qidong_4'],
      materials: [
        {
          mesh: '57_changjing',
          material: 'changjing',
        },
      ],
    },
    {
      name: 'One touch start',
      visibles: ['90_qidong_1', '91_qidong_2', '92_qidong_3', '93_qidong_4'],
      invisible: ['57_changjing'],
      materials: [],
    },
    {
      name: '555KM中配',
      visibles: [
        '01_car_body',
        '02_car_glass',
        '03_car_plastic',
        '03_car_plastic_dipei',
        '04_car_black_plastic',
        '05_car_chrome',
        '06_car_plane',
        '07_light_glass',
        '08_headlight_black_plastic',
        '09_headlight_chrome',
        '10_headlight_chrome_1',
        '11_car_logo_white',
        '12_car_map',
        '13_car_di_black',
        '14_taillight_black_plastic',
        '15_taillight_red_1',
        '16_taillight_red_2',
        '17_brake_disc_map_c',
        '18_before_tire',
        '22_after_tire',
        '26_car_inner',
        '27_car_inner_chair',
        '28_lf_door_body',
        '29_lf_door_chrome',
        '30_lf_door_black_plastic',
        '31_lf_door_glass',
        '32_lf_door_mirror',
        '33_lf_door_plastic',
        '34_lf_door_inner',
        '35_lb_door_body',
        '36_lb_door_chrome',
        '37_lb_door_plastic',
        '38_lb_door_glass',
        '39_lb_door_glass',
        '40_rf_door_body',
        '41_rf_door_chrome',
        '42_rf_door_black_plastic',
        '43_rf_door_plastic',
        '44_rf_door_mirror',
        '45_rf_door_glass',
        '46_rf_door_inner',
        '47_rb_door_body',
        '48_rb_door_chrome',
        '49_rb_door_plastic',
        '50_rb_door_glass',
        '51_rb_door_inner',
        '52_trunk_body',
        '53_trunk_chrome',
        '54_trunk_black_plastic',
        '55_trunk_inner',
        '56_trunk_plastic',
        '58_hub_before_black_plastic',
        '59_hub_before_chrome',
        '60_hub_before_white',
        '61_hub_after_black_plastic',
        '62_hub_after_chrome',
        '63_hub_after_white',
      ],
      invisible: [
        '03_car_plastic_siqu',
        '19_hub_before_chrome',
        '20_hub_before_black_plastic',
        '21_hub_before_white',
        '23_hub_after_chrome',
        '24_hub_after_black_plastic',
        '25_hub_after_white',
        '26_car_inner_red',
        '27_car_inner_chair_1',
        '34_lf_door_inner_1',
        '46_rf_door_inner_1',
        '65_car_leida_1',
        '66_car_leida_chrome_siqu',
        '67_car_leida_plastic_siqu',
      ],
      materials: [
        {
          mesh: '17_brake_disc_map_c',
          material: 'brake_disc_map_c',
        },
        {
          mesh: '02_car_glass_black',
          material: 'glass——white',
        },
        {
          mesh: '38_lb_door_glass',
          material: 'glass——white',
        },
        {
          mesh: '50_rb_door_glass',
          material: 'glass——white',
        },
      ],
    },
    {
      name: '555KM高配',
      visibles: [
        '01_car_body',
        '02_car_glass',
        '03_car_plastic',
        '04_car_black_plastic',
        '05_car_chrome',
        '06_car_plane',
        '07_light_glass',
        '08_headlight_black_plastic',
        '09_headlight_chrome',
        '10_headlight_chrome_1',
        '11_car_logo_white',
        '12_car_map',
        '13_car_di_black',
        '14_taillight_black_plastic',
        '15_taillight_red_1',
        '16_taillight_red_2',
        '17_brake_disc_map_c',
        '18_before_tire',
        '22_after_tire',
        '26_car_inner',
        '27_car_inner_chair',
        '28_lf_door_body',
        '29_lf_door_chrome',
        '30_lf_door_black_plastic',
        '31_lf_door_glass',
        '32_lf_door_mirror',
        '33_lf_door_plastic',
        '34_lf_door_inner',
        '34_lf_door_inner_1',
        '35_lb_door_body',
        '36_lb_door_chrome',
        '37_lb_door_plastic',
        '38_lb_door_glass',
        '39_lb_door_glass',
        '40_rf_door_body',
        '41_rf_door_chrome',
        '42_rf_door_black_plastic',
        '43_rf_door_plastic',
        '44_rf_door_mirror',
        '45_rf_door_glass',
        '46_rf_door_inner',
        '46_rf_door_inner_1',
        '47_rb_door_body',
        '48_rb_door_chrome',
        '49_rb_door_plastic',
        '50_rb_door_glass',
        '51_rb_door_inner',
        '52_trunk_body',
        '53_trunk_chrome',
        '54_trunk_black_plastic',
        '55_trunk_inner',
        '56_trunk_plastic',
        '58_hub_before_black_plastic',
        '59_hub_before_chrome',
        '60_hub_before_white',
        '61_hub_after_black_plastic',
        '62_hub_after_chrome',
        '63_hub_after_white',
        '65_car_leida_1',
      ],
      invisible: [
        '19_hub_before_chrome',
        '20_hub_before_black_plastic',
        '21_hub_before_white',
        '23_hub_after_chrome',
        '24_hub_after_black_plastic',
        '25_hub_after_white',
        '26_car_inner_red',
        '27_car_inner_chair_1',
        '66_car_leida_chrome_siqu',
        '67_car_leida_plastic_siqu',
      ],
      materials: [
        {
          mesh: '17_brake_disc_map_c',
          material: 'brake_disc_map_c',
        },
        {
          mesh: '02_car_glass_black',
          material: 'glass——white',
        },
        {
          mesh: '38_lb_door_glass',
          material: 'glass——white',
        },
        {
          mesh: '50_rb_door_glass',
          material: 'glass——white',
        },
      ],
    },
    {
      name: '705KM高配',
      visibles: [
        '01_car_body',
        '02_car_glass',
        '03_car_plastic',
        '04_car_black_plastic',
        '05_car_chrome',
        '06_car_plane',
        '07_light_glass',
        '08_headlight_black_plastic',
        '09_headlight_chrome',
        '10_headlight_chrome_1',
        '11_car_logo_white',
        '12_car_map',
        '13_car_di_black',
        '14_taillight_black_plastic',
        '15_taillight_red_1',
        '16_taillight_red_2',
        '17_brake_disc_map_c',
        '18_before_tire',
        '22_after_tire',
        '26_car_inner',
        '27_car_inner_chair',
        '27_car_inner_chair_1',
        '28_lf_door_body',
        '29_lf_door_chrome',
        '30_lf_door_black_plastic',
        '31_lf_door_glass',
        '32_lf_door_mirror',
        '33_lf_door_plastic',
        '34_lf_door_inner',
        '34_lf_door_inner_1',
        '35_lb_door_body',
        '36_lb_door_chrome',
        '37_lb_door_plastic',
        '38_lb_door_glass',
        '39_lb_door_glass',
        '40_rf_door_body',
        '41_rf_door_chrome',
        '42_rf_door_black_plastic',
        '43_rf_door_plastic',
        '44_rf_door_mirror',
        '45_rf_door_glass',
        '46_rf_door_inner',
        '46_rf_door_inner_1',
        '47_rb_door_body',
        '48_rb_door_chrome',
        '49_rb_door_plastic',
        '50_rb_door_glass',
        '51_rb_door_inner',
        '52_trunk_body',
        '53_trunk_chrome',
        '54_trunk_black_plastic',
        '55_trunk_inner',
        '56_trunk_plastic',
        '58_hub_before_black_plastic',
        '59_hub_before_chrome',
        '60_hub_before_white',
        '61_hub_after_black_plastic',
        '62_hub_after_chrome',
        '63_hub_after_white',
        '65_car_leida_1',
      ],
      invisible: [
        '19_hub_before_chrome',
        '20_hub_before_black_plastic',
        '21_hub_before_white',
        '23_hub_after_chrome',
        '24_hub_after_black_plastic',
        '25_hub_after_white',
        '26_car_inner_red',
        '66_car_leida_chrome_siqu',
        '67_car_leida_plastic_siqu',
      ],
      materials: [
        {
          mesh: '17_brake_disc_map_c',
          material: 'brake_disc_map_c',
        },
        {
          mesh: '50_rb_door_glass',
          material: 'glass',
        },
        {
          mesh: '38_lb_door_glass',
          material: 'glass',
        },
        {
          mesh: '02_car_glass_black',
          material: 'glass',
        },
      ],
    },
    {
      name: '600km四驱',
      visibles: [
        '01_car_body',
        '02_car_glass',
        '03_car_plastic',
        '03_car_plastic_siqu',
        '04_car_black_plastic',
        '05_car_chrome',
        '06_car_plane',
        '07_light_glass',
        '08_headlight_black_plastic',
        '09_headlight_chrome',
        '10_headlight_chrome_1',
        '11_car_logo_white',
        '12_car_map',
        '13_car_di_black',
        '14_taillight_black_plastic',
        '15_taillight_red_1',
        '16_taillight_red_2',
        '17_brake_disc_map_c',
        '18_before_tire',
        '19_hub_before_chrome',
        '20_hub_before_black_plastic',
        '21_hub_before_white',
        '22_after_tire',
        '23_hub_after_chrome',
        '24_hub_after_black_plastic',
        '25_hub_after_white',
        '26_car_inner',
        '26_car_inner_red',
        '27_car_inner_chair',
        '27_car_inner_chair_1',
        '28_lf_door_body',
        '29_lf_door_chrome',
        '30_lf_door_black_plastic',
        '31_lf_door_glass',
        '32_lf_door_mirror',
        '33_lf_door_plastic',
        '34_lf_door_inner',
        '34_lf_door_inner_1',
        '35_lb_door_body',
        '36_lb_door_chrome',
        '37_lb_door_plastic',
        '38_lb_door_glass',
        '39_lb_door_glass',
        '40_rf_door_body',
        '41_rf_door_chrome',
        '42_rf_door_black_plastic',
        '43_rf_door_plastic',
        '44_rf_door_mirror',
        '45_rf_door_glass',
        '46_rf_door_inner',
        '46_rf_door_inner_1',
        '47_rb_door_body',
        '48_rb_door_chrome',
        '49_rb_door_plastic',
        '50_rb_door_glass',
        '51_rb_door_inner',
        '52_trunk_body',
        '53_trunk_chrome',
        '54_trunk_black_plastic',
        '55_trunk_inner',
        '56_trunk_plastic',
        '65_car_leida_1',
        '66_car_leida_chrome_siqu',
        '67_car_leida_plastic_siqu',
      ],
      invisible: [
        '03_car_plastic_dipei',
        '58_hub_before_black_plastic',
        '59_hub_before_chrome',
        '60_hub_before_white',
        '61_hub_after_black_plastic',
        '62_hub_after_chrome',
        '63_hub_after_white',
      ],
      materials: [
        {
          mesh: '17_brake_disc_map_c',
          material: 'red_kaqian',
        },
        {
          mesh: '02_car_glass_black',
          material: 'glass',
        },
        {
          mesh: '38_lb_door_glass',
          material: 'glass',
        },
        {
          mesh: '50_rb_door_glass',
          material: 'glass',
        },
      ],
    },
    {
      name: 'scene1',
      visibles: ['57_changjing'],
      invisible: ['90_qidong_1', '91_qidong_2', '92_qidong_3', '93_qidong_4'],
      materials: [
        {
          mesh: '57_changjing',
          material: 'scene1',
        },
      ],
    },
    {
      name: 'hub_18',
      visibles: [
        '58_hub_before_black_plastic',
        '59_hub_before_chrome',
        '60_hub_before_white',
        '61_hub_after_black_plastic',
        '62_hub_after_chrome',
        '63_hub_after_white',
      ],
      invisible: [
        '19_hub_before_chrome',
        '20_hub_before_black_plastic',
        '21_hub_before_white',
        '23_hub_after_chrome',
        '24_hub_after_black_plastic',
        '25_hub_after_white',
      ],
      materials: [
        {
          mesh: '17_brake_disc_map_c',
          material: 'brake_disc_map_c',
        },
      ],
    },
    {
      name: 'hub_19',
      visibles: [
        '19_hub_before_chrome',
        '20_hub_before_black_plastic',
        '21_hub_before_white',
        '23_hub_after_chrome',
        '24_hub_after_black_plastic',
        '25_hub_after_white',
      ],
      invisible: [
        '58_hub_before_black_plastic',
        '59_hub_before_chrome',
        '60_hub_before_white',
        '61_hub_after_black_plastic',
        '62_hub_after_chrome',
        '63_hub_after_white',
      ],
      materials: [
        {
          mesh: '17_brake_disc_map_c',
          material: 'red_kaqian',
        },
      ],
    },
    {
      name: 'hub_19_heise',
      visibles: [
        '19_hub_before_chrome',
        '20_hub_before_black_plastic',
        '21_hub_before_white',
        '23_hub_after_chrome',
        '24_hub_after_black_plastic',
        '25_hub_after_white',
      ],
      invisible: [
        '58_hub_before_black_plastic',
        '59_hub_before_chrome',
        '60_hub_before_white',
        '61_hub_after_black_plastic',
        '62_hub_after_chrome',
        '63_hub_after_white',
      ],
      materials: [
        {
          mesh: '17_brake_disc_map_c',
          material: 'brake_disc_map_c',
        },
      ],
    },
  ],
  sprites: [],
  hotspots: [
    {
      name: 'lf_door_door',
      type: 'onoff',
      onAnimation: '',
      offAnimation: '',
      cameraPosition: {
        x: 0,
        y: 0,
        z: 0,
      },
      sprites: [],
      meshs: [
        '28_lf_door_body',
        '28_lf_door_body_1',
        '29_lf_door_chrome',
        '30_lf_door_black_plastic',
        '31_lf_door_glass',
        '32_lf_door_mirror',
        '33_lf_door_plastic',
        '33_lf_door_plastic_1',
        '34_lf_door_inner',
      ],
    },
    {
      name: 'lb_door_open',
      type: 'onoff',
      onAnimation: '',
      offAnimation: '',
      cameraPosition: {
        x: 0,
        y: 0,
        z: 0,
      },
      sprites: [],
      meshs: [
        '35_lb_door_body',
        '35_lb_door_body_1',
        '36_lb_door_chrome',
        '37_lb_door_plastic',
        '37_lb_door_plastic_1',
        '38_lb_door_glass',
        '39_lb_door_glass',
      ],
    },
    {
      name: 'rf_door_open',
      type: 'onoff',
      onAnimation: '',
      offAnimation: '',
      cameraPosition: {
        x: 0,
        y: 0,
        z: 0,
      },
      sprites: [],
      meshs: [
        '40_rf_door_body',
        '40_rf_door_body_1',
        '41_rf_door_chrome',
        '42_rf_door_black_plastic',
        '43_rf_door_plastic',
        '43_rf_door_plastic_1',
        '44_rf_door_mirror',
        '45_rf_door_glass',
        '46_rf_door_inner',
      ],
    },
    {
      name: 'rb_door_open',
      type: 'onoff',
      onAnimation: '',
      offAnimation: '',
      cameraPosition: {
        x: 0,
        y: 0,
        z: 0,
      },
      sprites: [],
      meshs: [
        '47_rb_door_body',
        '47_rb_door_body_1',
        '48_rb_door_chrome',
        '49_rb_door_plastic',
        '49_rb_door_plastic_1',
        '50_rb_door_glass',
        '51_rb_door_inner',
      ],
    },
    {
      name: 'trunk',
      type: 'onoff',
      onAnimation: '',
      offAnimation: '',
      cameraPosition: {
        x: 0,
        y: 0,
        z: 0,
      },
      sprites: [],
      meshs: [
        '54_trunk_black_plastic',
        '56_trunk_plastic',
        '53_trunk_chrome',
        '55_trunk_inner',
        '52_trunk_body',
      ],
    },
  ],
  hdr: 'studio_001.hdr',
}

export default config
