const external = {
  parameter: {
    name: 'DyglExternalCarParameter',
    unit: 'mm',
    font: '40pt droid_sans_regular, Avenir, Helvetica, Arial, sans-serif',
    fillStyle: '#FFF',
    length: {
      parameter: 4620,
      parameterPosition: { x: 0, y: 0.35, z: 1.6 },
      subline1: {
        point1: { x: -2.4, y: 0.35, z: 1.1 },
        point2: { x: -2.4, y: 0.35, z: 1.7 },
      },
      subline2: {
        point1: { x: 2.5, y: 0.35, z: 1.1 },
        point2: { x: 2.5, y: 0.35, z: 1.7 },
      },
      mainline: {
        point1: { x: -2.4, y: 0.35, z: 1.6 },
        point2: { x: 2.5, y: 0.35, z: 1.6 },
      },
    },
    width: {
      parameter: 1890,
      parameterPosition: { x: -2.8, y: 0.35, z: 0 },
      subline1: {
        point1: { x: -2.4, y: 0.35, z: -0.96 },
        point2: { x: -2.9, y: 0.35, z: -0.96 },
      },
      subline2: {
        point1: { x: -2.4, y: 0.35, z: 0.96 },
        point2: { x: -2.9, y: 0.35, z: 0.96 },
      },
      mainline: {
        point1: { x: -2.8, y: 0.35, z: 0.96 },
        point2: { x: -2.8, y: 0.35, z: -0.96 },
      },
    },
    height: {
      parameter: 1780,
      parameterPosition: { x: 0, y: 0.95, z: -1.6 },
      subline1: {
        point1: { x: 0, y: 0, z: -1.1 },
        point2: { x: 0, y: 0, z: -1.7 },
      },
      subline2: {
        point1: { x: 0, y: 1.8, z: -1.1 },
        point2: { x: 0, y: 1.8, z: -1.7 },
      },
      mainline: {
        point1: { x: 0, y: 0, z: -1.6 },
        point2: { x: 0, y: 1.8, z: -1.6 },
      },
    },
  },
  hotspot: {
    animate: {
      from: 0.15,
      to: 0.1,
      time: 1200,
    },
    door: {
      name: 'DyglExternalHotspotDoor',
      respones: [],
      type: 'door',
      texture: 'hot-dot.png',
      position: { x: -0.18, y: 0.87, z: 1.0 },
      lfDoor: {
        pivot: { x: -1.06533, y: 0, z: 0.87775 },
        models: [
          '31_lf_door_glass',
          '33_lf_door_plastic',
          '30_lf_door_black_plastic',
          '32_lf_door_mirror',
          '29_lf_door_chrome',
          '34_lf_door_inner',
          '28_lf_door_body',
          '28_lf_door_body_1',
          '33_lf_door_plastic_1',
          '34_lf_door_inner_1',
        ],
        axis: 'y',
        angle: 60,
        time: 1200,
        handle: {
          name: 'DyglExternalHotspotLFHandle',
          type: 'rotate',
          pivot: { x: 0.82444, y: 0, z: 0 },
          models: ['28_lf_door_body_1', '33_lf_door_plastic_1'],
          axis: 'y',
          angle: -25,
          time: 200,
        },
      },
      lbDoor: {
        pivot: { x: 0.0261, y: 0, z: 0.83775 },
        models: [
          '38_lb_door_glass',
          '36_lb_door_chrome',
          '37_lb_door_plastic',
          '39_lb_door_glass',
          '35_lb_door_body',
          '35_lb_door_body_1',
          '37_lb_door_plastic_1',
        ],
        axis: 'y',
        angle: 60,
        time: 1200,
        handle: {
          name: 'DyglExternalHotspotLBHandle',
          type: 'rotate',
          pivot: { x: 0.7126, y: 0, z: 0 },
          models: ['35_lb_door_body_1', '37_lb_door_plastic_1'],
          axis: 'y',
          angle: -25,
          time: 200,
        },
      },
      rfDoor: {
        pivot: { x: -1.06533, y: 0, z: -0.87775 },
        models: [
          '43_rf_door_plastic',
          '42_rf_door_black_plastic',
          '45_rf_door_glass',
          '46_rf_door_inner',
          '44_rf_door_mirror',
          '41_rf_door_chrome',
          '40_rf_door_body',
          '40_rf_door_body_1',
          '43_rf_door_plastic_1',
          '46_rf_door_inner_1',
        ],
        axis: 'y',
        angle: 60,
        time: 1200,
        handle: {
          name: 'DyglExternalHotspotRFHandle',
          type: 'rotate',
          pivot: { x: 0.82444, y: 0, z: 0 },
          models: ['40_rf_door_body_1', '43_rf_door_plastic_1'],
          axis: 'y',
          angle: 25,
          time: 200,
        },
      },
      rbDoor: {
        pivot: { x: 0.0261, y: 0, z: -0.83775 },
        models: [
          '49_rb_door_plastic',
          '48_rb_door_chrome',
          '50_rb_door_glass',
          '51_rb_door_inner',
          '47_rb_door_body',
          '47_rb_door_body_1',
          '49_rb_door_plastic_1',
        ],
        axis: 'y',
        angle: 60,
        time: 1200,
        handle: {
          name: 'DyglExternalHotspotRBHandle',
          type: 'rotate',
          pivot: { x: 0.7126, y: 0, z: 0 },
          models: ['47_rb_door_body_1', '49_rb_door_plastic_1'],
          axis: 'y',
          angle: 25,
          time: 200,
        },
      },
    },
    trunk: {
      name: 'DyglExternalHotspotTrunk',
      respones: [],
      type: 'trunk',
      texture: 'hot-dot.png',
      position: { x: 2.4, y: 0.81, z: 0 },
      pivot: { x: 1.59509, y: 1.19869, z: 0 },
      models: [
        '54_trunk_black_plastic',
        '56_trunk_plastic',
        '53_trunk_chrome',
        '55_trunk_inner',
        '52_trunk_body',
        '53_trunk_chrome_1',
      ],
      axis: 'z',
      angle: 65,
      time: 1200,
    },
    light: {
      name: 'DyglExternalHotspotLight',
      respones: [],
      type: 'light',
      texture: 'hot-dot.png',
      position: { x: -2.45, y: 0.7, z: -0.72 },
    },
    customs: [],
  },
  wheel: {
    floor: {
      name: 'wheel_play_floor',
      texture: 'road.jpg',
      size: {
        width: 100,
        height: 100,
      },
      repeat: {
        x: 40,
        y: 40,
      },
      speed: 0.04,
    },
    frontLeftWheel: {
      pivot: { x: -1.65892, y: 0.39026, z: 0 },
      models: [
        '18_before_tire',
        '19_hub_before_chrome',
        '20_hub_before_black_plastic',
        '21_hub_before_white',
        '58_hub_before_black_plastic',
        '59_hub_before_chrome',
        '60_hub_before_white',
      ],
    },
    frontRightWheel: {
      pivot: { x: -1.65892, y: 0.39026, z: 0 },
      models: [],
    },
    backWheel: {
      pivot: { x: 1.21492, y: 0.39026, z: 0 },
      models: [
        '22_after_tire',
        '23_hub_after_chrome',
        '24_hub_after_black_plastic',
        '25_hub_after_white',
        '61_hub_after_black_plastic',
        '62_hub_after_chrome',
        '63_hub_after_white',
      ],
    },
    speed: 1.5,
  },
  lights: [
    {
      name: 'DyglExternal_sprite_light1',
      texture: 'white-light.png',
      position: { x: -2.34, y: 0.84, z: 0.69 },
      scale: { x: 0.45, y: 0.45, z: 0.65 },
    },
    {
      name: 'DyglExternal_sprite_light3',
      texture: 'white-light.png',
      position: { x: -2.3, y: 0.84, z: 0.74 },
      scale: { x: 0.45, y: 0.45, z: 0.65 },
    },
    {
      name: 'DyglExternal_sprite_light2',
      texture: 'white-light.png',
      position: { x: -2.26, y: 0.84, z: 0.79 },
      scale: { x: 0.45, y: 0.45, z: 0.65 },
    },

    {
      name: 'DyglExternal_sprite_light4',
      texture: 'white-light.png',
      position: { x: -2.34, y: 0.84, z: -0.69 },
      scale: { x: 0.45, y: 0.45, z: 0.65 },
    },
    {
      name: 'DyglExternal_sprite_light6',
      texture: 'white-light.png',
      position: { x: -2.3, y: 0.84, z: -0.74 },
      scale: { x: 0.45, y: 0.45, z: 0.65 },
    },
    {
      name: 'DyglExternal_sprite_light5',
      texture: 'white-light.png',
      position: { x: -2.26, y: 0.84, z: -0.79 },
      scale: { x: 0.45, y: 0.45, z: 0.65 },
    },
  ],
}

export default external
